version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile           # your multi-stage Dockerfile should CMD “npm start” or similar
    ports:
      - '5050:5000'
    env_file:
      - .env.production                # keep only PROD env vars here
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
