services:
  api:
    image: cartierkuti/backend-api:prod
    env_file:
      - .env.prod
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  seed:
    image: cartierkuti/backend-api:prod
    env_file:
      - .env.prod
    entrypoint: ["npm", "run", "seed:prod"]
    depends_on:
      - api
    # run once, then exit
    restart: "no"

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
