services:
  api:
    build: .
    command: npm run dev
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_URL=${CLIENT_URL}
    depends_on:
      - mongo
    volumes:
      - ./:/backend
      - /backend/node_modules  # prevents override from local to container

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo-data:
