export const PROJECT_TAG_SUGGESTIONS = [
  'Business Planning',
  'Content Management',
  'Decision Support',
  'FIFA World Cup',
  'Football',
  'Operations',
  'Performance Analysis',
  'Personal Branding',
  'Portfolio',
  'Retail',
  'Sales',
]

export const PROJECT_METHOD_SUGGESTIONS = [
  'API Integration',
  'Automated Testing',
  'Batch Processing',
  'Classification',
  'Component-Based UI',
  'Cross-Validation',
  'Dashboard Design',
  'Data Validation',
  'Dimensional Modeling',
  'ETL',
  'Exploratory Data Analysis',
  'Feature Engineering',
  'KPI Design',
  'Model Evaluation',
  'Predictive Modeling',
  'Regression',
  'Responsive Design',
  'REST API Design',
  'Statistical Analysis',
  'Time-Series Forecasting',
  'Tournament Simulation',
  'Workflow Automation',
]

export const PROJECT_TOOL_SUGGESTIONS = [
  'Docker',
  'Express',
  'GitHub Actions',
  'JavaScript',
  'MongoDB',
  'Node.js',
  'NumPy',
  'pandas',
  'PostgreSQL',
  'Power BI',
  'Python',
  'React',
  'scikit-learn',
  'SQL',
  'Tableau',
  'TypeScript',
  'Vite',
]
